node {
  timestamps()
  stage('Checkout') {
    checkout scm
  }
  stage('Verificar Docker no agente') {
    sh 'docker --version'
    sh 'docker info > /dev/null'
  }
  stage('Build da imagem') {
    sh "docker build -t unicamp-5-2:${env.BUILD_NUMBER} ."
  }
  stage('Executar app no container') {
    sh "docker run --rm unicamp-5-2:${env.BUILD_NUMBER}"
  }
  stage('Cleanup') {
    sh 'docker image prune -f || true'
  }
}

